spring:
  application:
    name: SpringAI

  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: qwen2.5:3b
    openai:
      chart:
        options:
          model: gpt-4o-mini
          temperature: 0.9
      embedding:
        options:
          model: text-embedding-3-small

    vectorstore:
      pgvector:
        initialize-schema: true

  datasource:
    url: jdbc:postgresql://localhost:5434/my-vector-db
    username: my-user
    password: password
    driver-class-name: org.postgresql.Driver

logging:
  level:
    org.springframework.ai:
      chat.client: DEBUG